import turtle as trtl

painter = trtl.Turtle()

painter.penup()
painter.hideturtle()
painter.goto(-300,300)
painter.showturtle()
painter.pendown()
painter.pencolor('red')
painter.speed(1)
painter.turtlesize(1)
painter.pensize(1)
painter.forward(100)
painter.turtlesize(2)
painter.pensize(2)
painter.right(90)
painter.pencolor('orange')
painter.speed(2)
painter.forward(125)
painter.turtlesize(3)
painter.pensize(3)
painter.left(90)
painter.pencolor('yellow')
painter.speed(3)
painter.forward(150)
painter.turtlesize(4)
painter.pensize(4)
painter.right(90)
painter.pencolor('green')
painter.speed(4)
painter.forward(175)
painter.turtlesize(5)
painter.pensize(5)
painter.left(90)
painter.pencolor('lightblue')
painter.speed(5)
painter.forward(200)
painter.turtlesize(6)
painter.pensize(6)
painter.right(90)
painter.pencolor('blue')
painter.speed(7)
painter.forward(225)
painter.turtlesize(6)
painter.pensize(6)
painter.left(90)
painter.pencolor('purple')
painter.speed(8)
painter.forward(250)
painter.turtlesize(7)
painter.pensize(7)

wn = trtl.Screen()
wn.mainloop()

