import turtle as trtl

painter = trtl.Turtle()
painter.speed(0)
painter.penup()
painter.goto(100,50)
painter.pendown()
painter.circle(50)
painter.penup()
painter.goto(-100,50)
painter.pendown()
painter.circle(50)
painter.penup()
painter.goto(-100,75)
painter.pendown()
painter.circle(25)
painter.penup()
painter.goto(100,75)
painter.pendown()
painter.circle(25)
painter.penup()
painter.goto(0,45)
painter.pendown()
painter.goto(10,-5)
painter.right(180)
painter.forward(45)
painter.penup()
painter.goto(-55,-30)
painter.pendown()
painter.left(90)
painter.circle(50,180)
painter.penup()
painter.goto(197,50)
painter.pendown()
painter.circle(200)


wn = trtl.Screen()
wn.mainloop()